### ISSUE TITLE
`internal_token.txt` is changed on FF update

### ISSUE THREAD

**Issue by CanuckMarc** [NubeIO/flow-framework#576]
When FF is updated/installed the `internal_token.txt` is changed.  

value before update: `eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjAyNTY3NDQsImlhdCI6MTY1NzY2NDc0NCwic3ViIjoiaW50ZXJuYWxfdXNlciJ9.Gg6kOZHTHKJ898631r2_4jUCXAkKCI9kMfmja_FkKuM`

value after update:
`eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjA0NDQ3OTAsImlhdCI6MTY1Nzg1Mjc5MCwic3ViIjoiaW50ZXJuYWxfdXNlciJ9.h296ivPgROGNeVJ16Y7s6JO_1VxepnNunyCGOVtMmNI`

Also good to note that the first chunk of the token is the same as before (@NubeDev looking at the first digits doesn't mean it hasn't changed)

**Comment by RaiBnod** [comment]
The `rubix-service` was used to reset the `internal_token` each time before version: `v1.19.4` and it was valid because `internal_token` were been used by just the `rubix-service` app.

Now, `internal_token` is used by `flow-framework` too. So, it needs to be consistent throughout both `rubix-service` and `flow-framework`. So, we are not resetting that `internal_token` from the `rubix-service` version `v1.19.4`.

**So the fix is:** use that rubix-service version: `v1.19.4` or latest.

**Comment by CanuckMarc** [comment]
@RaiBnod  I just tested the token on Rubix Service `v1.19.5`.  I found that the `internal_token.txt` token changes ON EACH REBOOT.  

These are my findings from doing 2 reboot tests on Rubix Service `v1.19.5`:
Original Token:
`eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjA2OTIyODMsImlhdCI6MTY1ODEwMDI4Mywic3ViIjoiaW50ZXJuYWxfdXNlciJ9.B2VdQeWSO-PiOcywkbkNfAIvThTxmP3HLbED1DTEv8E`

After Reboot 1:
`eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjA2OTU3MDAsImlhdCI6MTY1ODEwMzcwMCwic3ViIjoiaW50ZXJuYWxfdXNlciJ9.bKqgZuKlorvk83GzC6E-gr8JpCMptXB3Ds-WG8FrxCo`

After Reboot 2:
`eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjA2OTU5MzcsImlhdCI6MTY1ODEwMzkzNywic3ViIjoiaW50ZXJuYWxfdXNlciJ9.WSp9PGwwVTpOOTk6kffF2k90-2ogLJgDRsU0DA0t0dY`

**Comment by RaiBnod** [comment]
Will be resolved by this: https://github.com/NubeIO/rubix-service/pull/290
